[package]
name = "liquid_staking"
edition = "2024.beta"

[addresses]
liquid_staking = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
